# Site settings
name: Dmitri Tsoy
email: dmitri@tsoy.org
#canonical_url: https://dmitri.tsoy.org
keywords: "Lead Software Engineer"
skills: "Software Engineer"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/dmitritsoy/
  - title: stackoverflow
    url: https://stackoverflow.com/users/2394328/dmitri-tsoy
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0B3B7A
  primary-rgb: "214, 90, 47"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: compact # possible values: nested expanded compact compressed